apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
  - ../../base
  - staging-ingress.yaml

patches:
  - target:
      kind: Deployment
      name: monitoring-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "96Mi"
            cpu: "70m"
          limits:
            memory: "192Mi"
            cpu: "150m"
  - path: configmap-patch.yaml

images:
  - name: monitoring-frontend
    newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-dashboard-ui
    newTag: latest # Replace with ${CI_COMMIT_SHORT_SHA} in GitLab CI